const contract = {
	abi: [
		{
			"constant":false,
			"inputs":[],
			"name":"contractDone",
			"outputs":[],
			"payable":false,
			"stateMutability":"nonpayable",
			"type":"function"
		},
		{
			"constant":false,
			"inputs":[],
			"name":"contractNotDone",
			"outputs":[],
			"payable":true,
			"stateMutability":"payable",
			"type":"function"
		},
		{
			"constant":false,
			"inputs":[
				{
					"name":"role",
					"type":"bytes32"
				},
				{
					"name":"addr",
					"type":"address"
				}
			],
			"name":"approve",
			"outputs":[
				{
					"name":"",
					"type":"uint256"
				}
			],
			"payable":false,
			"stateMutability":"nonpayable",
			"type":"function"
		},
		{
			"constant":false,
			"inputs":[
				{
					"name":"role","type":"bytes32"
				},
				{
					"name":"addr","type":"address"
				}
			],
			"name":"addParticipant",
			"outputs":[
				{
					"name":"","type":"uint256"
				}
			],
			"payable":false,
			"stateMutability":"nonpayable",
			"type":"function"
		},
		{
			"constant":false,
			"inputs":[],
			"name":"checkProgress",
			"outputs":[
				{
					"name":"","type":"uint256[2]"
				}
			],
			"payable":false,
			"stateMutability":"nonpayable",
			"type":"function"
		},
		{
			"constant":false,
			"inputs":[
				{
					"name":"prod",
					"type":"address"
				},
				{
					"name":"cust","type":"address"
				}
			],
			"name":"init",
			"outputs":[],
			"payable":false,
			"stateMutability":"nonpayable",
			"type":"function"
		}
	],
	address: "0x25f2be34a672d6aed19eae00f49fffed623be754"
}

module.exports = contract;